### ISSUE TITLE
Convert to use Prettier test infra

### ISSUE THREAD

**Issue by azz** [benjie/prettier-plugin-pg-sql#2]
In the other plugins I have set up we've copied Prettier's `run_spec` infrastructure as it super nice to add and review tests.

`run_spec`: https://github.com/prettier/prettier-php/blob/master/tests_config/run_spec.js
Example test directory: https://github.com/prettier/prettier-php/tree/master/tests/declare

Should be easy to set up but better do it sooner than later 😄

**Comment by benjie** [comment]
Definitely support being consistent with the rest of the ecosystem (didn't to start with because I can set up jest in like 3 seconds flat, so it was the obvious choice when it was just an experiment). I can get this done over the weekend, unless anyone beats me to it with a PR!

**Comment by benjie** [comment]
Oooo, very pretty. Done: https://github.com/benjie/prettier-plugin-pg-sql/commit/013905823ace977f09b46a09acce0742b39c2e4f
